### ISSUE TITLE
Question - hook up generated Jersey (from RAML) without routes

### ISSUE THREAD

**Issue by shale99** [ef-labs/vertx-jersey#47]
I have generated classes from RAML - I would like to know if it is possible to make asynchronous calls to these classes - if so, can this be done without having to declare routes? 
Any help would be greatly appreciated

**Comment by adrianluisgonzalez** [comment]
Do you have an example project you can share?

**Comment by zeevs** [comment]
hi,
sorry for the delay - put something ad hoc together quickly to show the use case as the project is still not prod yet.
this is run with 
-javaagent:C:\Users\shale\.m2\repository\co\paralleluniverse\quasar-core\0.7.4\quasar-core-0.7.4.jar
basically the restverticle is run
and a sample path would be 
http://localhost:8080/apis/configurations/tables
[RestAPI.zip](https://github.com/englishtown/vertx-jersey/files/163697/RestAPI.zip)

a ton of thanks for any feedback

**Comment by adrianluisgonzalez** [comment]
I think I understand what you want to do.

Looking at `RestVerticle`, you are deploying an instance of `JerseyVerticle` with rest resources `com.sling.rest.impl` which contains `com.sling.rest.impl.ConfigAPI`.  `ConfigAPI` implements interface `com.sling.rest.jaxrs.resource.ConfigurationsResource`.

The problem is the `ConfigurationResource` is not an asynchronous interface.  To make async JAX-RS calls, you must inject a `@Suspended AsyncResponse asyncResponse`.

https://jersey.java.net/documentation/latest/async.html

If you are forced to use ConfigurationResource, then you could consider `vertx-sync` which allows you to block on a quasar fiber.  I have not tried to use that myself with Jersey, I am not sure if anything would need to change to support this.

Hope this helps.

**Comment by zeevs** [comment]
Will definitely look into that
Much appreciated!

**Comment by zeevs** [comment]
Got this working by taking your jersey verticle and basically having it extend the syncverticle - then use the await result sync functions in the jersey implementations. Do you see a major problem with that?

**Comment by adrianluisgonzalez** [comment]
Hard to say without seeing the code, but approach sounds correct to me.
